apiVersion: v1
kind: ConfigMap
metadata:
  name: status-reporter-config
  namespace: dev
data:
  RABBITMQ_HOST: "rabitmq-cluster"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "slack_send_message_queue"
  RABBITMQ_USER: "GDS_service_QA"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-reporter
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: status-reporter-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: status-reporter-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: status-reporter
  namespace: dev
roleRef:
  kind: Role
  name: status-reporter-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: status-reporter
  namespace: dev
spec:
  # Run daily at 8:00 AM UTC
  schedule: "0 8 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: status-reporter
        spec:
          serviceAccountName: status-reporter
          restartPolicy: OnFailure
          containers:
          - name: reporter
            image: gcr.io/crx-dev-svc/status-reporter:latest
            imagePullPolicy: Always
            env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: status-reporter-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: status-reporter-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: status-reporter-config
                  key: RABBITMQ_QUEUE
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: status-reporter-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-gds-qa
                  key: password
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
