apiVersion: v1
kind: ConfigMap
metadata:
  name: qa-status-reporter-config
  namespace: dev
data:
  RABBITMQ_HOST: "rabitmq-cluster"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "slack_send_message_queue"
  RABBITMQ_USER: "GDS_service_QA"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qa-status-reporter
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-status-reporter-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-status-reporter-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qa-status-reporter-role
subjects:
- kind: ServiceAccount
  name: qa-status-reporter
  namespace: dev
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: qa-status-reporter
  namespace: dev
spec:
  # Run daily at 8:00 AM UTC
  schedule: "0 8 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: qa-status-reporter
        spec:
          serviceAccountName: qa-status-reporter
          restartPolicy: OnFailure
          containers:
          - name: reporter
            # Using Artifact Registry (same as gds_service)
            image: us-east4-docker.pkg.dev/crx-infra-svc/crx-infra-docker/qa-status-reporter:qa-latest
            imagePullPolicy: Always
            env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: qa-status-reporter-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: qa-status-reporter-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: qa-status-reporter-config
                  key: RABBITMQ_QUEUE
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: qa-status-reporter-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-gds-qa
                  key: password
